# Main navigation menu

[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Posts"
  pageRef = "/posts/"
  weight = 20

[[main]]
  name = "Product"
  pageRef = "/categories/catholic-gifts/"
  weight = 25

[[main]]
  name = "Catholic Gifts"
  url = "https://mecrt.com/"
  weight = 30

[[main]]
  name = "Catholic Rosary"
  url = "https://ctoco.com/"
  weight = 40
